//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsWebApp {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsWebApp.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///  {
        ///    &quot;guid&quot;: &quot;ce521f9c-a504-4fd1-8213-e26010b99377&quot;,
        ///    &quot;id&quot;: 0,
        ///    &quot;firstName&quot;: &quot;Helen&quot;,
        ///    &quot;lastName&quot;: &quot;Pena&quot;
        ///  },
        ///  {
        ///    &quot;guid&quot;: &quot;cec9f84c-00f6-4a3f-b35f-c97400498107&quot;,
        ///    &quot;id&quot;: 1,
        ///    &quot;firstName&quot;: &quot;Fay&quot;,
        ///    &quot;lastName&quot;: &quot;French&quot;
        ///  },
        ///  {
        ///    &quot;guid&quot;: &quot;da75aa6f-3179-4feb-9761-a5cbae9347cc&quot;,
        ///    &quot;id&quot;: 2,
        ///    &quot;firstName&quot;: &quot;Branch&quot;,
        ///    &quot;lastName&quot;: &quot;Madden&quot;
        ///  },
        ///  {
        ///    &quot;guid&quot;: &quot;ca9c87d4-0221-4a9e-bbda-b60c1f105e1a&quot;,
        ///    &quot;id&quot;: 3,
        ///    &quot;firstName&quot;: &quot;Kennedy&quot;,
        ///    &quot;lastName&quot;: &quot;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data_People {
            get {
                return ResourceManager.GetString("Data_People", resourceCulture);
            }
        }
    }
}
